## Kafka resource requests and limits
resources: 	
  limits:	
    cpu: 400m	
    memory: 400Mi	
  requests:	
    cpu: 200m	
    memory: 256Mi


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
          - key: "Infra-Services"
            operator: In
            values:
            - "true"